### ISSUE TITLE
error with install 

### ISSUE THREAD

**Issue by j-avila** [abe33/atom-color-highlight#104]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [atom-color-highlight](https://github.com/abe33/atom-color-highlight) package, v3.0.9

### Stack Trace

Failed to load the atom-color-highlight package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\jose avila\.atom\packages\atom-color-highlight-master\lib\atom-color-highlight.coffee:1:34)
  at Object.<anonymous> (C:\Users\jose avila\.atom\packages\atom-color-highlight-master\lib\atom-color-highlight.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:709:34)
  at C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:188:28
  at Package.module.exports.Package.measure (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.load (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:336:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\atom.js:638:21)
  at Object.<anonymous> (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\jose avila\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/jose%20avila/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/jose%20avila/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.10
emmet, v2.3.12
wakatime, v4.0.12

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi, this package have been unpublished and replaced by [pigments](http://atom.io/packages/pigments).
