### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by stramel** [abe33/atom-color-highlight#68]
**OS:** Ubuntu 14.04
**Atom:** 0.167.0-8f4555b
**atom-color-highlight:** 3.0.2

I get this error when attempting to split panes into two vertical panes. 

```bash
/home/stramel/.atom/packages/atom-color-highlight/lib/atom-color-highlight.coffee:58
```

```bash
// Stack Trace
TypeError: Cannot read property 'appendChild' of null
  at /home/stramel/.atom/packages/atom-color-highlight/lib/atom-color-highlight.coffee:58:41
  at /usr/local/share/atom/resources/app/src/workspace.js:273:16
  at /usr/local/share/atom/resources/app/src/workspace.js:330:18
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/local/share/atom/resources/app/src/pane-container.js:379:27)
  at /usr/local/share/atom/resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/local/share/atom/resources/app/src/pane.js:334:20)
  at PaneView._results.push._this.(anonymous function) [as addItem] (/usr/local/share/atom/resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at Pane.module.exports.Pane.moveItemToPane (/usr/local/share/atom/resources/app/src/pane.js:418:19)
  at PaneView._results.push._this.(anonymous function) [as moveItemToPane] (/usr/local/share/atom/resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at atom-pane.<anonymous> (/home/stramel/.atom/packages/pain-split/lib/pain-split.coffee:30:22)
  at atom-pane.handler (/usr/local/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-pane.jQuery.event.dispatch (/usr/local/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-pane.elemData.handle (/usr/local/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/local/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/local/share/atom/resources/app/src/window-event-handler.js:167:20)
```

**Comment by abe33** [comment]
Hmm, I can't reproduce it (same atom version but on OSX), I've got the colors from the initial that disappears (which didn't occurs before today's Atom version) but otherwise no errors.

**Comment by stramel** [comment]
@abe33 could be Linux only issue, thanks for looking into it!

**Comment by abe33** [comment]
Seems like a recent update in Atom changed the way panes are split by detaching/reattaching the panes and editors, I'll publish some changes tonight hoping it'll fix this in your setup (I can just guess what could go wrong here).
