### ISSUE TITLE
Error: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by SalGnt** [abe33/atom-color-highlight#76]
I found this error on console and I noticed that it is caused by this package and by the [atom-project-palette-finder](https://github.com/abe33/atom-project-palette-finder/) package.

It occurs when I launch Atom and I have one of your packages enabled. It occurs even when I try to enable one of the two package.

I'm using Atom Version `0.177.0`.

```
Arguments to path.resolve must be strings TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:423:13)
  at new PathScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/scandal/lib/path-scanner.js:25:28)
  at Object.module.exports (/Applications/Atom.app/Contents/Resources/app/src/scan-handler.js:12:15)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:84:10)
  at process.emit (events.js:119:17)
  at handleMessage (child_process.js:326:10)
  at Pipe.channel.onread (child_process.js:354:11)
```

**Comment by abe33** [comment]
Thanks for the report, can you give me the version of `atom-color-highlight` and `project-palette-finder` too?

**Comment by SalGnt** [comment]
Sure, I'm using the latest versions.
* `atom-color-highlight 3.0.6`
* `project-palette-finder 2.4.13`
