### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by idris** [abe33/atom-color-highlight#83]
This randomly happens when I focus Atom.

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-color-highlight](https://github.com/abe33/atom-color-highlight) package, v3.0.8

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

TypeError: undefined is not a function
  at color-marker.module.exports.MarkerMixin.intersectsRenderedScreenRows (/Users/idris/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:50:45)
  at color-marker.module.exports.MarkerMixin.isVisible (/Users/idris/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:28:6)
  at color-marker.module.exports.MarkerMixin.isUpdateNeeded (/Users/idris/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:47:6)
  at color-marker.module.exports.MarkerElement.updateDisplay (/Users/idris/.atom/packages/atom-color-highlight/lib/marker-element.coffee:19:20)
  at /Users/idris/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:35:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:114:32
  at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/signal.js:82:19)
  at DisplayBuffer.module.exports.Model.set (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:166:21)
  at DisplayBuffer.accessor.set (/Applications/Atom.app/Contents/Resources/app/node_modules/theorist/lib/model.js:57:23)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:448:31)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1430:21)
  at /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:351:27)
  at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:56:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:590:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:503:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:475:35
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextBuffer.module.exports.TextBuffer.setTextViaDiff (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:452:19)
  at TextBuffer.module.exports.TextBuffer.reload (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:979:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1100:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/event-kit/lib/emitter.js:35:25)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:337:38
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
     -0:01.3 application:new-file (input.hidden-input)
     -0:00.7 core:paste (input.hidden-input)
     -0:00.4 core:select-all (input.hidden-input)
     -0:00.3 core:copy (input.hidden-input)
     -0:00.0 core:close (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
monokai, v0.12.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
I think your Atom version is too old for this version of the package. Updating Atom to its latest version should fix this issue.

**Comment by idris** [comment]
I'm using the latest version of Atom (0.165.0)

**Comment by abe33** [comment]
You are not using the latest version of Atom.

Latest public version is 0.184.0, see here: https://github.com/atom/atom/releases

**Comment by idris** [comment]
Whoops :dizzy_face:

**Comment by wmleler** [comment]
I am using 0.184.0 and I'm getting a ton of these errors.

**Comment by wmleler** [comment]
Updated my packages, and now I'm just getting a few of the occasionally.

**Comment by abe33** [comment]
@wmleler Thanks for the follow up, what I really need, if possible, is a reproducible test case. I'm using it everyday and didn't had such issue so I can't confirm the issue unless I'm provided with steps to reproduce the errors. 
Also, it's really important to provides the various versions and packages installed as there's some interactions between some of them (this package for instance will use the Color object from the project-palette-finder package when both are installed).
