### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

### ISSUE THREAD

**Issue by muchweb** [abe33/atom-color-highlight#84]
Happens when quickly doing loads of undo and redo.

---

**Atom Version**: 0.184.0
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [atom-color-highlight](https://github.com/abe33/atom-color-highlight) package, v3.0.8

### Stack Trace

Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

```
At /usr/share/atom/resources/app/src/tokenized-buffer.js:559

TypeError: Cannot read property 'tokenAtBufferColumn' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenForPosition (/usr/share/atom/resources/app/src/tokenized-buffer.js:559:38)
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/usr/share/atom/resources/app/src/tokenized-buffer.js:552:22)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/usr/share/atom/resources/app/src/display-buffer.js:1042:35)
  at color-marker.module.exports.MarkerMixin.getScope (/home/muchweb/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:59:42)
  at color-marker.module.exports.MarkerMixin.hiddenDueToComment (/home/muchweb/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:67:14)
  at color-marker.module.exports.MarkerMixin.isHidden (/home/muchweb/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:53:6)
  at color-marker.module.exports.MarkerMixin.show (/home/muchweb/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:18:33)
  at atom-color-highlight.AtomColorHighlightElement.updateSelections (/home/muchweb/.atom/packages/atom-color-highlight/lib/atom-color-highlight-element.coffee:82:10)
  at /home/muchweb/.atom/packages/atom-color-highlight/lib/atom-color-highlight-element.coffee:59:8

**Comment by abe33** [comment]
I'm not sure how I can prevent that but I'll take a look, anyway, thanks for the report!
