### ISSUE TITLE
Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by nwork** [abe33/atom-color-highlight#88]
I have no idea why this started happening, I haven't used atom in a few weeks and when I loaded it couple of days ago I get 3 errors.

[Enter steps to reproduce below:]

1. Happens during loading of application

**Atom Version**: 0.188.0
**System**: linux 3.11.0-26-generic
**Thrown From**: [atom-project-manager-master](https://github.com/danielbrodin/atom-project-manager) package, v1.15.1

### Stack Trace

Failed to load the atom-project-manager-master package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/w0und/.atom/packages/atom-project-manager-master/lib/project-manager-add-view.coffee:7:10)
    at Object.<anonymous> (/home/w0und/.atom/packages/atom-project-manager-master/lib/project-manager-add-view.coffee:109:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/opt/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-color-highlight-master, v3.0.5
atom-minimap-master, v3.5.6
atom-project-manager-master, v1.15.1
auto-host-markdown-image, v0.2.3
file-icons, v1.5.2
file-icons-master, v1.4.8
minimap, v4.7.1
project-manager, v1.15.5

# Dev
No dev packages
```

I get the same error for atom-color-highlight, atom-minimap and atom-project-manager

**Comment by abe33** [comment]
Hmm, weird indeed. 
Have you checked if the missing modules were properly installed in the packages' `node_modules` directory?
Have you tried reinstalling the packages?
My guess is that since 0.187 Atom switched to Chrome 41 there's a chance that some packages dependencies may need to be recompiled against the new chrome headers.
