### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/Restuta/.atom/packages/atom-color-highlight/lib/marker-view.coffee'

### ISSUE THREAD

**Issue by Restuta** [abe33/atom-color-highlight#90]
Steps:
1. open `styles.less`
2. type anything with color like `color: blue;`

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-color-highlight](https://github.com/abe33/atom-color-highlight) package, v3.0.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Restuta/.atom/packages/atom-color-highlight/lib/marker-view.coffee'

```
At /Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:126

Error: ENOENT: no such file or directory, open '/Users/Restuta/.atom/packages/atom-color-highlight/lib/marker-view.coffee'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Object.exports._compileFile (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:221:14)
  at getSourceMap (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:329:22)
  at getSourceMapping (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:337:19)
  at formatSourcePosition (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:289:16)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:355:34
  at Function.Error.prepareStackTrace (/Applications/Atom.app/Contents/Resources/app/node_modules/season/node_modules/cson-parser/node_modules/coffee-script/lib/coffee-script/coffee-script.js:358:7)
  at trackRejection (/Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:988:32)
  at reject (/Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:1044:5)
  at _fulfilled (/Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:789:20)
  at self.promiseDispatch.done (/Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:749:13)
  at /Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:557:44
  at flush (/Users/Restuta/.atom/packages/atom-color-highlight/node_modules/pigments/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
  3x -6:28.3 tree-view:toggle (div.settings-view.pane-item)
 10x -4:59.2 core:backspace (atom-text-editor.editor.mini)
     -4:09.8 window:toggle-dev-tools (atom-text-editor.editor.mini)
     -3:31.8 core:backspace (atom-text-editor.editor.mini)
     -3:30.2 application:open-your-stylesheet (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-one-dark-ui)
  3x -3:28.4 editor:newline (atom-text-editor.editor)
  4x -3:19.2 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-color-highlight": {}
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-plus, v2.11.0
color-picker, v1.7.0
file-icons, v1.5.4
filetype-color, v0.1.4
highlight-line, v0.10.2
javascript-snippets, v1.0.0
jsformat, v0.8.0
language-csharp, v0.5.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
I believe you've got this issues after an update?

The `marker-view` was replaced by `marker-element` in version 3.0.0 so you must have updated from that version I guess. A restart should fix that, there's still some issue when updating packages in Atom, sometimes the new code doesn't get reloaded and so, if the file structure changes it may raise exception because the old code doesn't find the removed files.

**Comment by Restuta** [comment]
@abe33 restart didn't fix that :(
