### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by fly-racoon** [abe33/atom-color-highlight#97]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-color-highlight](https://github.com/abe33/atom-color-highlight) package, v3.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660

TypeError: Cannot read property 'getTokenIterator' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660:42)
  at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1135:35)
  at color-marker.module.exports.MarkerMixin.getScope (/Users/createuser/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:59:42)
  at color-marker.module.exports.MarkerMixin.hiddenDueToComment (/Users/createuser/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:67:14)
  at color-marker.module.exports.MarkerMixin.isHidden (/Users/createuser/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:53:6)
  at color-marker.module.exports.MarkerMixin.show (/Users/createuser/.atom/packages/atom-color-highlight/lib/marker-mixin.coffee:18:33)
  at atom-color-highlight.AtomColorHighlightElement.updateSelections (/Users/createuser/.atom/packages/atom-color-highlight/lib/atom-color-highlight-element.coffee:82:10)
  at /Users/createuser/.atom/packages/atom-color-highlight/lib/atom-color-highlight-element.coffee:39:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:101:27)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:150:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
 16x -0:21.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:19.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:19 snippets:expand (atom-text-editor.editor.is-focused)
     -0:19 editor:indent (atom-text-editor.editor.is-focused)
     -0:18.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 30x -0:18.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:15.1.0 editor:newline (atom-text-editor.editor.is-focused)
 14x -0:14.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:12.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:11.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  5x -0:11.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:10.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:10 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet",
      "pomodoro"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-color-highlight, v3.0.9
autoclose-html, v0.18.0
file-icons, v1.5.7
fonts, v0.4.2
linter, v0.12.7
linter-csslint, v0.0.13
linter-jshint, v0.1.6
linter-less, v0.5.0
seti-syntax, v0.4.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @fly-racoon, I'm no longer maintaining this package, it has been replaced with [pigments](http://atom.io/packages/pigments).
